# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "centos/7"
    config.vm.box_version = "2004.01"
  
    config.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 1
    end
  
    config.vm.define "web" do |web|
      web.vm.network "private_network", ip: "192.168.50.10"
      web.vm.hostname = "web"
    end
  
    config.vm.define "log" do |log|
      log.vm.network "private_network", ip: "192.168.50.15"
      log.vm.hostname = "log"
    end
  
  end